configuration: Release
branches:
  only:
  - master
  - dev
  - /hotfix\/.*/

environment:
  SignClientSecret:
    secure: S26+NphAhj/vo5ZdHd/N/4toty3ztdNGmuNdvAB57W1oIVQEHVKqAVuhTD8B9ATy

install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
  - cmd: nuget install GitVersion.CommandLine -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre  
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
  - cmd: nuget install SignClient -Version 0.5.0-beta4 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
     
before_build:
  - cmd: nuget restore src\Humanizer.sln
  - cmd: '.\packages\GitVersion.CommandLine\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo'
  
build:
  verbosity: normal
  parallel: true
  project: src\Humanizer.sln
  
after_build:
  - ps: |
      $nugetVer = $env:GitVersion_NuGetVersion
      if(![string]::IsNullOrWhiteSpace($env:GitVersion_BuildMetaDataPadded)) {
        $nugetVer = $nugetVer + "-build$env:GitVersion_BuildMetaDataPadded"
      }  
      ls .\NuSpecs\*.nuspec | %{ nuget pack $_.FullName -version "$nugetVer" -BasePath "src" -NoPackageAnalysis }
  - ps: '.\scripts\Sign-Package.ps1'        
  - ps: 'ls *.nupkg | %{ appveyor PushArtifact $_.Name}'
  
test:
  assemblies:
    - '**\*.Tests.dll'
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/humanizer/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/